### ISSUE TITLE
Doesn't lint on-the-fly nor on save

### ISSUE THREAD

**Issue by bobrocke** [AtomLinter/linter-less#19]
OS X 10.11
Atom 1.0.19
linter-less 2.2.0

 which less
/usr/bin/less

Include Path set to: /usr/bin/less

**Comment by josa42** [comment]
`linter-less` is a bundled version of `less` to lint files so it should even work without less installed. The include path in the settings is passed `less` and used for imports (See: [Using Less: Include Paths](http://lesscss.org/usage/)).

I can't reproduce your issue. Can provide more information?

* do you have the linter package installed?
* I there any error in the console? (View -> Developer -> Toggle Developer Tools)
* Does it work with only linter and linter-less activated?

**Comment by bobrocke** [comment]
I changed the Include Path to null.

I have linter v1.8.1 installed.

Nothing is in the console.

It behaves the same with other linters off.

New information:

It does show errors on save.

If I am in a .scss file with errors and switch to a .less file without errors, the error count from the .scss file remains in the info bar at the bottom of the view. If I create a new error in the .less file, the errors shown in the info bar are incremented by one. So perhaps it is working on-the-fly, but not properly handling to info bar display?

**Comment by bobrocke** [comment]
OK, it looks to be my error combined with my misunderstanding.

linter-less is working fine, I believe.

I had the scope of the linter mis-set to Project instead of File.

I'm sorry to have wasted your time. :(

**Comment by josa42** [comment]
No problem. I am glad your problem got resolved.
