### ISSUE TITLE
Allow checks for undefined variables to be disabled

### ISSUE THREAD

**Issue by SolusSoftworks** [AtomLinter/linter-less#9]
I pass variables to the less file when I process it meaning the variables are not defined in the file itself. This leads to variable undefined errors which make the package useless for the rest of the file. It would be preferable to have the option to disable checks for this. Perhaps checks for a special type of comment `// @variable_name` could be introduced to define external variables which will prevent the error without affecting the less output yet still allow locally defined variables to be monitored.

**Comment by josa42** [comment]
I added an option to "ignore undefined variables", which is off by default but can be activated in the settings of linter-less. Let me know if that resolves the issue for you.

**Comment by SolusSoftworks** [comment]
Thanks. Seems to work so far. :)
